# This is a config for E2B sandbox template.
# You can use 'template_id' (427ccdjm2prdgsnh57p2) or 'template_name (mukul-test-2) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='mukul-test-2')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'mukul-test-2' })

team_id = "51ab042f-2389-487f-a6de-5b1535a24a28"
dockerfile = "e2b.Dockerfile"
template_name = "mukul-test-2"
template_id = "427ccdjm2prdgsnh57p2"
