# This is a config for E2B sandbox template.
# You can use 'template_id' (vzut1xq0gtthjy167zec) or 'template_name (mukul-test-1) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='mukul-test-1')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'mukul-test-1' })

team_id = "51ab042f-2389-487f-a6de-5b1535a24a28"
start_cmd = "/root/.jupyter/start-up.sh"
dockerfile = "e2b.Dockerfile"
template_name = "mukul-test-1"
template_id = "vzut1xq0gtthjy167zec"
